apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment
  labels:
    run: nginx
spec:
  selector:
    app: nginx
    run: nginx
  ports:
    - port: 80
      protocol: TCP
  type: LoadBalancer
